DROP TABLE IF EXISTS projects 
GO


CREATE TABLE projects (
    PROJECT_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    PROJECT_DESC VARCHAR(50) NOT NULL,
    PROJECT_START_DT CHAR(8) NOT NULL,
    PROJECT_END_DT CHAR(8),
    PROJECT_ACTIVE BIT NOT NULL,
    PROJECT_END_REASON VARCHAR(50),
    PARENT_PROJECT VARCHAR(20),
);


--CREATE TABLE projects (
--    PROJECT_ID VARCHAR(20) NOT NULL PRIMARY KEY,
--    PROJECT_DESC VARCHAR(50) NOT NULL,
--    PROJECT_START_DT CHAR(8) NOT NULL,
--    PROJECT_END_DT CHAR(8),
--    PROJECT_ACTIVE BIT NOT NULL,
--    PROJECT_END_REASON VARCHAR(50),
--    PARENT_PROJECT VARCHAR(20),
--    CONSTRAINT fk_parent_project FOREIGN KEY (PARENT_PROJECT) REFERENCES projects(PROJECT_ID),
--    CONSTRAINT ck_project_end_reason CHECK (PROJECT_END_REASON IN ('scheduled end', 'funding', 'obsolete', 'executive decision', 'other') OR PROJECT_END_REASON IS NULL),
--    CONSTRAINT ck_project_active CHECK ((PROJECT_ACTIVE = 0 AND PROJECT_END_DT IS NOT NULL) OR (PROJECT_ACTIVE = 1 AND PROJECT_END_DT IS NULL)),
--    CONSTRAINT ck_dates CHECK (PROJECT_START_DT <= PROJECT_END_DT OR PROJECT_END_DT IS NULL)
--);